const $ = (id) => document.getElementById(id);
const ui = { app: document.querySelector('.app-shell'), camera: $('camera'), fallback: $('fallback'), arena: $('arena'), projectiles: $('projectileLayer'), start: $('startScreen'), end: $('endCard'), turn: $('turnCard'), combat: $('combatHud'), bottom: $('bottomHud'), attacks: $('attackBar'), fire: $('fireButton'), dodge: $('dodgeButton'), playerHp: $('playerHealth'), enemyHp: $('enemyHealth'), playerNum: $('playerHealthNumber'), enemyNum: $('enemyHealthNumber'), timer: $('timer'), charge: $('chargeBar'), toast: $('toast'), flash: $('damageFlash'), mode: $('modeLabel') };
const ENEMY_TYPES = [
  { id: 'drone', name: 'DRONE', hp: 100, damage: 7, className: 'enemy-drone' },
  { id: 'wraith', name: 'WRAITH', hp: 125, damage: 11, className: 'enemy-wraith' },
  { id: 'brute', name: 'BRUTE', hp: 170, damage: 16, className: 'enemy-brute' },
  { id: 'splitter', name: 'SPLITTER', hp: 85, damage: 5, className: 'enemy-splitter' }
];
const ATTACKS = { pulse: { name: 'PULSE', cost: 12, damage: 17 }, nova: { name: 'NOVA', cost: 30, damage: 42 }, freeze: { name: 'FREEZE', cost: 22, damage: 25 } };
let state = { mode: 'ai', active: false, player: 100, enemy: 100, enemyType: ENEMY_TYPES[0], selectedAttack: 'pulse', frozen: false, dodgeUntil: 0, heading: 0, pitch: 0, anchor: { yaw: 0, pitch: 0, depth: 4 }, time: 60, shots: 0, hits: 0, charge: 100, timerId: null, enemyId: null, turn: 1, pvpScores: [0, 0], stream: null, cameraRequested: false, sound: true };

document.querySelectorAll('.mode-card').forEach(card => card.addEventListener('click', () => { document.querySelector('.mode-card.selected').classList.remove('selected'); card.classList.add('selected'); state.mode = card.dataset.mode; }));
$('launchButton').addEventListener('click', start);
$('restartButton').addEventListener('click', start);
$('turnButton').addEventListener('click', beginTurn);
ui.fire.addEventListener('click', fire);
ui.dodge.addEventListener('click', dodge);
window.addEventListener('deviceorientationabsolute', updateOrientation, true);
window.addEventListener('deviceorientation', updateOrientation, true);
document.querySelectorAll('.attack').forEach(button => button.addEventListener('click', () => { if (!state.active) return; document.querySelector('.attack.selected')?.classList.remove('selected'); button.classList.add('selected'); state.selectedAttack = button.dataset.attack; showToast(ATTACKS[state.selectedAttack].name + ' ARMED', '#55f6ff'); }));
ui.arena.addEventListener('click', (e) => { if (state.active && !e.target.closest('.enemy')) fire(); });
function showPanel(panel, display = 'flex') { panel.hidden = false; panel.style.display = display; }
function hidePanel(panel) { panel.hidden = true; panel.style.display = 'none'; }
$('soundButton').addEventListener('click', () => { state.sound = !state.sound; $('soundButton').textContent = state.sound ? '◖))' : '◖×'; });

function start() {
  // Start gameplay immediately. Camera permissions can take time on mobile and must never block replay.
  reset(); hidePanel(ui.start); hidePanel(ui.end); hidePanel(ui.turn); ui.mode.textContent = state.mode === 'ai' ? 'SOLO // AI' : 'PASS & PLAY';
  getCamera(); requestMotionPermission();
  if (state.mode === 'pvp') { showTurnIntro(); } else beginRound();
}
async function requestMotionPermission() { try { if (typeof DeviceOrientationEvent?.requestPermission === 'function') await DeviceOrientationEvent.requestPermission(); } catch { showToast('MOTION TRACKING OFF', '#ffcf65'); } }
async function getCamera() {
  if (state.stream || state.cameraRequested || !navigator.mediaDevices?.getUserMedia) return;
  state.cameraRequested = true;
  try { state.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); ui.camera.srcObject = state.stream; ui.fallback.style.display = 'none'; }
  catch { ui.fallback.style.display = 'block'; showToast('SIMULATION MODE', '#ffcf65'); }
}
function updateOrientation(event) { const heading = event.webkitCompassHeading ?? (event.alpha == null ? state.heading : 360 - event.alpha); state.heading = heading || state.heading; state.pitch = event.beta || 0; positionEnemy(); }
function positionEnemy() { const enemy = document.querySelector('.enemy'); if (!enemy) return; const yawDelta = ((((state.anchor.yaw - state.heading) + 540) % 360) - 180) * Math.PI / 180; const focal = Math.min(innerWidth, innerHeight) * 0.9; const x = innerWidth / 2 + Math.tan(yawDelta) * focal; const y = innerHeight / 2 + (state.anchor.pitch - state.pitch) * 4; const scale = Math.max(.45, Math.min(1.5, 4 / (state.anchor.depth + Math.abs(yawDelta) * 1.8))); enemy.style.left = `${x - enemy.offsetWidth / 2}px`; enemy.style.top = `${y - enemy.offsetHeight / 2}px`; enemy.style.setProperty('--depth-scale', scale); enemy.style.transform = `scale(${scale}) rotateY(${yawDelta * 28}deg)`; }
function reset() { clearInterval(state.timerId); clearInterval(state.enemyId); ui.arena.innerHTML = ''; ui.projectiles.innerHTML = ''; Object.assign(state, { active:false, player:100, enemy:100, enemyType:ENEMY_TYPES[0], selectedAttack:'pulse', frozen:false, dodgeUntil:0, anchor:{yaw:state.heading,pitch:state.pitch,depth:4}, time:60, shots:0, hits:0, charge:100, turn:1, pvpScores:[0,0] }); document.querySelector('.attack.selected')?.classList.remove('selected'); document.querySelector('[data-attack="pulse"]')?.classList.add('selected'); updateHud(); }
function showTurnIntro() { ui.turn.hidden = false; $('turnTitle').innerHTML = `PLAYER ${state.turn}<br />READY?`; $('turnText').textContent = state.turn === 1 ? 'Aim for the target. You have 10 seconds to score.' : 'Pass the phone. Beat Player 1’s score!'; }
function beginTurn() { hidePanel(ui.turn); state.time = state.mode === 'pvp' ? 10 : 60; beginRound(); }
function beginRound() { state.active = true; showPanel(ui.combat, 'grid'); showPanel(ui.bottom, 'grid'); showPanel(ui.attacks, 'flex'); $('playerName').textContent = state.mode === 'pvp' ? `P${state.turn}` : 'YOU'; $('enemyName').textContent = state.mode === 'pvp' ? `P${state.turn === 1 ? 2 : 1}` : 'SENTINEL'; spawnEnemy(); state.timerId = setInterval(() => { state.time--; ui.timer.textContent = state.time; if (state.time <= 0) finish(); }, 1000); if (state.mode === 'ai') state.enemyId = setInterval(enemyAttack, 1900); }
function spawnEnemy() { const old = document.querySelector('.enemy'); if (old) old.remove(); state.enemyType = ENEMY_TYPES[Math.floor(Math.random() * ENEMY_TYPES.length)]; state.enemy = state.enemyType.hp; state.frozen = false; state.anchor = { yaw: (state.heading + (-32 + Math.random() * 64) + 360) % 360, pitch: -12 + Math.random() * 24, depth: 3.2 + Math.random() * 2.2 }; const enemy = document.createElement('button'); enemy.className = `enemy ${state.enemyType.className}`; enemy.setAttribute('aria-label', `${state.enemyType.name} target`); enemy.innerHTML = `<span class="label">${state.enemyType.name} // LOCK</span>`; enemy.addEventListener('click', hitEnemy); ui.arena.append(enemy); positionEnemy(); updateHud(); showToast(`${state.enemyType.name} INBOUND`, '#ff7aad'); }
function hitEnemy(e) { e.stopPropagation(); castAttack(state.selectedAttack, e.currentTarget); }
function launchProjectile(kind, target, onImpact) { const bolt = document.createElement('div'); bolt.className = `projectile projectile-${kind}`; ui.projectiles.append(bolt); const rect = target?.getBoundingClientRect(); const tx = rect ? rect.left + rect.width / 2 : innerWidth / 2; const ty = rect ? rect.top + rect.height / 2 : innerHeight / 2; bolt.style.setProperty('--tx', `${tx - innerWidth / 2}px`); bolt.style.setProperty('--ty', `${ty - innerHeight / 2}px`); requestAnimationFrame(() => bolt.classList.add('travelling')); setTimeout(() => { bolt.remove(); onImpact(); }, kind === 'enemy' ? 900 : 420); }
function castAttack(id, target = document.querySelector('.enemy')) { const attack = ATTACKS[id]; if (!state.active || !target) return; if (state.charge < attack.cost) { showToast('NOT ENOUGH CHARGE', '#ffcf65'); return; } state.shots++; state.charge -= attack.cost; updateHud(); showToast(`${attack.name} LAUNCHED`, '#55f6ff'); launchProjectile(id, target, () => { if (!state.active) return; state.hits++; state.enemy = Math.max(0, state.enemy - attack.damage); if (id === 'freeze') state.frozen = true; target.classList.add('hit'); ping(id === 'nova' ? 760 : 540, .06); updateHud(); showToast(`${attack.name} IMPACT // -${attack.damage}`, '#55f6ff'); setTimeout(() => { if (!state.active) return; if (state.enemy <= 0) { target.remove(); showToast('TARGET DOWN — NEW THREAT', '#55f6ff'); setTimeout(spawnEnemy, 260); } else target.classList.remove('hit'); }, 210); }); }
function fire() { castAttack(state.selectedAttack); }
function dodge() { if (!state.active) return; state.dodgeUntil = Date.now() + 900; ui.app?.classList.add('dodging'); showToast('DODGE WINDOW', '#55f6ff'); setTimeout(() => ui.app?.classList.remove('dodging'), 300); }
function enemyAttack() { if (!state.active || state.frozen) { state.frozen = false; return; } showToast(`${state.enemyType.name} FIRES — DODGE!`, '#ff7aad'); launchProjectile('enemy', document.querySelector('.enemy'), () => { if (!state.active) return; if (Date.now() < state.dodgeUntil) { showToast('ATTACK DODGED', '#55f6ff'); return; } state.player = Math.max(0, state.player - (state.enemyType.damage + Math.floor(Math.random() * 5))); ui.flash.classList.add('show'); setTimeout(() => ui.flash.classList.remove('show'), 100); ping(90, .13); updateHud(); if (state.player <= 0) finish(false); }); }
function updateHud() { ui.playerHp.style.width = `${state.player}%`; ui.enemyHp.style.width = `${state.enemy}%`; ui.playerNum.textContent = state.player; ui.enemyNum.textContent = state.enemy; ui.timer.textContent = state.time; ui.charge.style.width = `${state.charge}%`; }
function finish(won) { if (!state.active) return; state.active = false; clearInterval(state.timerId); clearInterval(state.enemyId); ui.arena.innerHTML = ''; ui.combat.hidden = true; ui.bottom.hidden = true; ui.attacks.hidden = true; if (state.mode === 'pvp') state.pvpScores[state.turn - 1] = state.hits; if (state.mode === 'pvp' && state.turn === 1) { state.turn = 2; state.player = 100; state.enemy = 100; state.time = 10; state.hits = 0; state.shots = 0; showTurnIntro(); return; } ui.end.hidden = false; const pvp = state.mode === 'pvp'; $('resultTag').textContent = pvp ? 'MATCH COMPLETE' : won ? 'COMBAT COMPLETE' : 'SYSTEM FAILURE'; $('resultTitle').innerHTML = pvp ? (state.pvpScores[0] === state.pvpScores[1] ? 'PERFECT<br />DRAW' : `PLAYER ${state.pvpScores[0] > state.pvpScores[1] ? '1' : '2'}<br />WINS`) : won ? 'TARGET<br />ELIMINATED' : 'YOU WERE<br />HUNTED'; $('resultText').textContent = pvp ? 'The camera arena has chosen its champion.' : won ? 'The arena is clear. Excellent work.' : 'The Sentinel got the better of you this round.'; document.querySelector('.result-stats span:first-child').firstChild.textContent = pvp ? 'P1 HITS ' : 'ACCURACY '; document.querySelector('.result-stats span:last-child').firstChild.textContent = pvp ? 'P2 HITS ' : 'HITS '; $('accuracy').textContent = pvp ? state.pvpScores[0] : (state.shots ? `${Math.round(state.hits / state.shots * 100)}%` : '0%'); $('hits').textContent = pvp ? state.pvpScores[1] : state.hits; }
function showToast(message, color) { ui.toast.textContent = message; ui.toast.style.color = color; ui.toast.classList.add('show'); clearTimeout(showToast.id); showToast.id = setTimeout(() => ui.toast.classList.remove('show'), 650); }
function ping(freq, duration) { if (!state.sound || !window.AudioContext) return; const ctx = ping.ctx ||= new AudioContext(); const osc = ctx.createOscillator(), gain = ctx.createGain(); osc.frequency.value = freq; gain.gain.setValueAtTime(.045, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + duration); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + duration); }
setInterval(() => { if (state.active && state.charge < 100) { state.charge = Math.min(100, state.charge + 3); updateHud(); } }, 180);
